CREATE TABLE users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  name text not null,
  password text not null,
  role text not null,
  email text not null
);

CREATE TABLE products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  title text not null,
  description text not null,
  price int4 not null,
  image text not null,
  is_deleted bool default false not null
);

CREATE TABLE orders (
  id bigint generated by default as identity primary key,
  user_id bigint NOT NULL REFERENCES users(id),
  status bool default false not null
);

CREATE TABLE order_products (
  order_id bigint NOT NULL REFERENCES orders(id),
  product_id bigint NOT NULL REFERENCES products(id),
  quantity int4 not null,
  PRIMARY KEY (order_id, product_id)
);